version: '3'


volumes:
    prometheus_data: {}
    grafana_data: {}




services:

  #TSDB
  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

    depends_on:
      - adapteur 
    restart: always
    network_mode: "host"

  #modbus-adapteur app 
  adapteur:
    build: .
    image: cynergie-adapter
    ports:
      - 3002:3002
    network_mode: "host"

  #used to show graphics
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - config.monitoring
    command:
      - '--config=/etc/grafana/grafana.ini'
    network_mode: "host"


